import { useEffect, useRef, useState } from 'react';
import { Bell, ChevronDown, Heart, LogOut, Search, User as UserIcon } from 'lucide-react';
import type { User } from '../../types/auth';
export interface SiteNavbarProps { user: User | null; onSignIn: () => void; onSignOut: () => void; onHome: () => void; onWishlist: () => void; }
export function SiteNavbar({ user, onSignIn, onSignOut, onHome, onWishlist }: SiteNavbarProps) {
  const [profile, setProfile] = useState(false); const [notifications, setNotifications] = useState(false); const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!menuRef.current?.contains(event.target as Node)) { setProfile(false); setNotifications(false); } }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  return <header className="sticky top-0 z-40 border-b border-white/10 bg-[#4A2D1F] text-white shadow-sm"><nav className="page-shell flex h-16 min-w-0 flex-nowrap items-center justify-between gap-1 sm:h-18 sm:gap-3" aria-label="Main navigation"><div className="flex min-w-0 items-center gap-5"><button onClick={onHome} className="flex min-w-0 items-center gap-1.5 rounded-lg min-[375px]:gap-2 sm:gap-3"><img src="/brew-logo.png" alt="" className="h-8 w-8 shrink-0 rounded-full object-cover ring-1 ring-white/25 min-[375px]:h-9 min-[375px]:w-9 sm:h-10 sm:w-10" /><span className="truncate whitespace-nowrap text-sm font-bold min-[375px]:text-base sm:text-lg">Brew Finder</span></button><div className="hidden items-center gap-5 text-sm font-semibold text-[#F4ECE6] lg:flex"><a href="#discover">Discover</a><a href="#map">Map</a><a href="#collections">Collections</a></div></div>
    <div ref={menuRef} className="relative flex shrink-0 flex-nowrap items-center gap-0 min-[375px]:gap-0.5 sm:gap-2"><button aria-label="Search" onClick={() => document.querySelector<HTMLInputElement>('[data-testid=coffee-search-input]')?.focus()} className="nav-icon hidden lg:grid"><Search /></button><button onClick={onWishlist} aria-label="Open wishlist" className="nav-icon sm:w-auto sm:gap-2 sm:px-3"><Heart /><span className="hidden sm:inline">Wishlist</span></button><button aria-label="Notifications" onClick={() => { setNotifications(!notifications); setProfile(false); }} className="nav-icon"><Bell /></button>
      {notifications && <div className="fixed right-3 top-[4.5rem] z-50 w-[min(18rem,calc(100vw-1.5rem))] rounded-2xl border border-[#EAE3D8] bg-white p-4 text-[#241711] shadow-xl sm:absolute sm:right-11 sm:top-14"><p className="font-bold">Notifications</p><p className="mt-2 text-sm text-[#6F675F]">You’re all caught up.</p></div>}
      {user ? <div className="relative"><button aria-label="Open account menu" onClick={() => { setProfile(!profile); setNotifications(false); }} className="flex min-h-11 min-w-11 items-center justify-center rounded-full hover:bg-white/10"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#B5663D] text-sm font-bold">{user.name?.charAt(0).toUpperCase() || 'U'}</span><ChevronDown className="hidden h-4 w-4 sm:block" /></button>{profile && <div className="fixed right-3 top-[4.5rem] z-50 w-[min(16rem,calc(100vw-1.5rem))] rounded-2xl border border-[#EAE3D8] bg-white p-2 text-[#241711] shadow-xl sm:absolute sm:right-0 sm:top-14"><div className="border-b px-3 py-3"><p className="truncate font-bold">{user.name}</p><p className="truncate text-xs text-[#6F675F]">{user.email}</p></div><button onClick={onWishlist} className="menu-item"><Heart />My wishlist</button><button onClick={onSignOut} className="menu-item text-red-700"><LogOut />Log out</button></div>}</div> : <button onClick={onSignIn} aria-label="Sign in" className="grid min-h-11 min-w-11 place-items-center rounded-full bg-[#FAF7F0] px-1.5 text-sm font-bold text-[#4A2D1F] sm:block sm:px-4"><span className="hidden sm:inline">Sign in</span><UserIcon className="h-5 w-5 sm:hidden" /></button>}
    </div></nav></header>;
}
