import { useState } from 'react';
import { MapPin } from 'lucide-react';
import type { CoffeeShop, UserLocation } from '../../types/restaurant';
import { NearbyMap } from './NearbyMap';
export interface ExploreNearbySectionProps { shops: CoffeeShop[]; location?: UserLocation | null; onRequestLocation?: () => void; onOpen: (shop: CoffeeShop) => void; }
export function ExploreNearbySection({ shops, location, onRequestLocation, onOpen }: ExploreNearbySectionProps) {
  const visible = shops.slice(0, 5); const [selectedId, setSelectedId] = useState<string | null>(null); const selected = visible.find((shop) => shop.id === selectedId) ?? visible[0] ?? null;
  return <section id="map" className="page-shell section-space"><div className="min-w-0 overflow-hidden rounded-[24px] bg-[#28613E] text-white sm:rounded-[28px] lg:grid lg:grid-cols-[minmax(280px,0.8fr)_minmax(0,1.2fr)]"><div className="min-w-0 p-6 sm:p-10 lg:p-12"><p className="text-xs font-bold tracking-[.18em] text-[#C9DFC8]">YOUR NEXT CUP, CLOSER</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Explore nearby</h2><p className="mt-3 max-w-md text-sm text-[#E1EBE1] sm:text-base">Choose a café to move the interactive map, then get directions when you are ready.</p><div className="no-scrollbar mt-5 hidden max-w-full gap-2 overflow-x-auto pb-1 sm:flex lg:flex-wrap">{visible.map((shop) => <button key={shop.id} onClick={() => setSelectedId(shop.id)} aria-pressed={selected?.id === shop.id} className="shrink-0 rounded-full border border-white/30 bg-white/10 px-3 py-2 text-xs font-bold aria-pressed:bg-white aria-pressed:text-[#28613E]">{shop.name}</button>)}</div><button onClick={onRequestLocation} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-white px-5 font-bold text-[#28613E] sm:w-auto"><MapPin className="h-4 w-4" />{location ? 'Refresh location' : 'Use my location'}</button></div><NearbyMap shops={visible} location={location} selected={selected} onSelect={(shop) => setSelectedId(shop.id)} onOpen={onOpen} /></div></section>;
}
