import { Crosshair, Search, X } from 'lucide-react';
import type { LocationError, UserLocation } from '../../types/restaurant';
import { FilterChips } from './FilterChips';
export interface HeroSearchPanelProps { search: string; onSearchChange: (value: string) => void; township: string; townships: string[]; onTownshipChange: (value: string) => void; activeFilter: string | null; onFilterChange: (value: string | null) => void; nearMeActive: boolean; location?: UserLocation | null; locationLoading: boolean; locationError?: LocationError | null; onNearMe: () => void; }
export function HeroSearchPanel(props: HeroSearchPanelProps) {
  return <div className="flex min-w-0 flex-col justify-center"><p className="mb-4 text-xs font-bold tracking-[.16em] text-[#B5663D] sm:tracking-[.2em]">GOOD COFFEE. A BRIGHTER YANGON.</p><h1 className="max-w-2xl text-4xl font-bold leading-[1.06] tracking-[-.035em] sm:text-5xl lg:text-6xl">Find your perfect coffee spot</h1><p className="mt-5 max-w-xl text-base leading-7 text-[#6F675F] sm:text-lg">Discover the best cafés in Yangon — from cozy hideaways to vibrant community spaces.</p>
    <div className="mt-8 grid min-w-0 gap-2 rounded-2xl border border-[#EAE3D8] bg-white p-2 shadow-soft sm:grid-cols-[minmax(0,1fr)_180px_auto] sm:gap-0"><label className="flex min-h-12 min-w-0 items-center gap-2 px-2 sm:gap-3 sm:px-3"><Search className="h-5 w-5 shrink-0 text-[#6F675F]" /><span className="sr-only">Search cafés</span><input data-testid="coffee-search-input" value={props.search} onChange={(event) => props.onSearchChange(event.target.value)} placeholder="Search cafés, neighborhoods or vibes" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#8C847C]" />{props.search && <button aria-label="Clear search" onClick={() => props.onSearchChange('')} className="icon-button shrink-0"><X className="h-4 w-4" /></button>}</label><select aria-label="Select township" value={props.township} onChange={(event) => props.onTownshipChange(event.target.value)} className="min-h-12 min-w-0 w-full rounded-xl bg-transparent px-3 text-sm font-semibold outline-none"><option value="all">All townships</option>{props.townships.map((township) => <option key={township}>{township}</option>)}</select><button onClick={props.onNearMe} disabled={props.nearMeActive && props.locationLoading} aria-pressed={props.nearMeActive} className={`button-primary w-full sm:w-auto ${props.nearMeActive ? 'ring-2 ring-[#28613E] ring-offset-2' : ''}`}><Crosshair className="h-4 w-4" />{props.nearMeActive && props.locationLoading ? 'Finding you...' : props.nearMeActive && props.location ? 'Nearest first' : 'Near me'}</button></div>
    {props.nearMeActive && props.locationError && <p role="alert" className="mt-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{props.locationError.message}</p>}<FilterChips active={props.activeFilter} onChange={props.onFilterChange} />
  </div>;
}
